### ISSUE TITLE
CI CD 스크립트 작성

### ISSUE THREAD

**Issue by yanJuicy** [Challenge-Hanbang-E/Hanbang-E#53]
## ✍ Description
CI CD 스크립트 작성

## Todo
- [ ] github acitons CI CD 스크립트 작성
- [ ] ec2 배포 스크립트 작성
- [ ] docker 배포 스크립트 작성
